RelativeURLs=true
CanonifyURLs=true
languageCode = "en-US"
defaultContentLanguage = "en"

title = "AWS Application Migration Workshop"
theme = "learn"
metaDataFormat = "yaml"
defaultContentLanguageInSubdir= true

uglyurls = true
sectionPagesMenu = "main"
pygmentsCodeFences = true
pygmentsStyle = "monokai"

[markup.goldmark.renderer]
unsafe= true

[params]
  editURL = "https://github.com/aws-samples/application-migration-with-aws-workshop/edit/master/workshop/content/"
  description = "AWS Application Migration Workshop"
  author = "Ahmed Omran, Lech Migdal"
  disableBreadcrumb = false
  disableNextPrev = false
  themeVariant = "aws"
  disableSearch = false
  disableAssetsBusting = true
  disableLanguageSwitchingButton = false
  disableShortcutsTitle = true
  disableInlineCopyToClipBoard = true


  [[menu.shortcuts]]
  name = "<i class='fab fa-github'></i> GitHub Project"
  url = "https://github.com/aws-samples/application-migration-with-aws-workshop"
  weight = 30

  [[menu.shortcuts]]
  name = "<i class='fas fa-envelope'></i> Have questions?"
  url = "mailto:application-migration-workshop@amazon.com"
  weight = 40

  [[menu.shortcuts]]
  name = "<i class='fas fa-poll'></i> Rate the workshop"
  url = "https://amazonmr.au1.qualtrics.com/jfe/form/SV_0dfrnubGKXavgR7"
  weight = 50

  [[menu.shortcuts]]
  name = "<i class='fas fa-book-open'></i> More resources"
  url = "https://aws.amazon.com/cloud-migration/resources/"
  weight = 60


[outputs]
home = [ "HTML", "RSS", "JSON"]

[blackfriday]
plainIDAnchors = true
hrefTargetBlank = false

[Languages]
[Languages.en]
title = "AWS Application Migration Workshop"
weight = 1
languageName = "English"

[Languages.ja]
title = "アプリケーション移行ワークショップ"
weight = 1
languageName = "Japanese（日本語）"

  [[Languages.ja.menu.shortcuts]]
  name = "<i class='fab fa-github'></i> GitHub リポジトリ"
  url = "https://github.com/aws-samples/application-migration-with-aws-workshop"
  weight = 30

  [[Languages.ja.menu.shortcuts]]
  name = "<i class='fas fa-envelope'></i> 内容に関するお問い合わせ"
  url = "mailto:application-migration-workshop@amazon.com"
  weight = 40

  [[Languages.ja.menu.shortcuts]]
  name = "<i class='fas fa-poll'></i> ワークショップの評価"
  url = "https://amazonmr.au1.qualtrics.com/jfe/form/SV_0dfrnubGKXavgR7"
  weight = 50

  [[Languages.ja.menu.shortcuts]]
  name = "<i class='fas fa-book-open'></i> 参考資料"
  url = "https://aws.amazon.com/cloud-migration/resources/"
  weight = 60